@startuml

title __MODEL's Class Diagram__\n

  namespace com.cleanup.todoc {
    namespace model {
      class com.cleanup.todoc.model.Project {
          - color : int
          - id : long
          - name : String
          {static} + getAllProjects()
          + getColor()
          + getId()
          + getName()
          {static} + getProjectById()
          + setColor()
          + setId()
          + setName()
          + toString()
          - Project()
      }
    }
  }
  

  namespace com.cleanup.todoc {
    namespace model {
      class com.cleanup.todoc.model.Task {
          + creationTimestamp : long
          + projectId : long
          - id : long
          - name : String
          + Task()
          + getId()
          + getName()
          + getProjectId()
          - setCreationTimestamp()
          - setId()
          - setName()
          - setProjectId()
      }
    }
  }
  

  namespace com.cleanup.todoc {
    namespace model {
      class com.cleanup.todoc.model.Task.TaskAZComparator {
          + compare()
      }
    }
  }
  

  namespace com.cleanup.todoc {
    namespace model {
      class com.cleanup.todoc.model.Task.TaskOldComparator {
          + compare()
      }
    }
  }
  

  namespace com.cleanup.todoc {
    namespace model {
      class com.cleanup.todoc.model.Task.TaskRecentComparator {
          + compare()
      }
    }
  }
  

  namespace com.cleanup.todoc {
    namespace model {
      class com.cleanup.todoc.model.Task.TaskZAComparator {
          + compare()
      }
    }
  }
  

  com.cleanup.todoc.model.Task +-down- com.cleanup.todoc.model.Task.TaskAZComparator
  com.cleanup.todoc.model.Task +-down- com.cleanup.todoc.model.Task.TaskOldComparator
  com.cleanup.todoc.model.Task +-down- com.cleanup.todoc.model.Task.TaskRecentComparator
  com.cleanup.todoc.model.Task +-down- com.cleanup.todoc.model.Task.TaskZAComparator
  com.cleanup.todoc.model.Task.TaskAZComparator .up.|> java.util.Comparator
  com.cleanup.todoc.model.Task.TaskOldComparator .up.|> java.util.Comparator
  com.cleanup.todoc.model.Task.TaskRecentComparator .up.|> java.util.Comparator
  com.cleanup.todoc.model.Task.TaskZAComparator .up.|> java.util.Comparator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
